# start from an official image
FROM python:3.9.4
ENV PYTHONUNBUFFERED=1

# arbitrary location choice: you can change the directory
RUN mkdir -p /opt/services/djangoapp/src
WORKDIR /opt/services/djangoapp/src

# install our dependencies
# we use --system flag because we don't need an extra virtualenv
#COPY Pipfile Pipfile.lock /opt/services/djangoapp/src/
#RUN pip install pipenv && pipenv install --system
COPY requirements.txt /opt/services/djangoapp/src/
RUN pip install -r requirements.txt

# copy our project code
COPY . /opt/services/djangoapp/src
#RUN cd calendar_events && python manage.py collectstatic --no-input -v 2
RUN python manage.py collectstatic --no-input -v 2

# expose the port 8000
EXPOSE 80

# define the default command to run when starting the container
CMD ["gunicorn", "--chdir", "calendar_events", "--bind", ":80", "calendar_events.wsgi:application"]